### ISSUE TITLE
Search filter values are lost when you click a results row to see details

### ISSUE THREAD

**Issue by neekfenwick** [zencart/email-archive-manager#3]
- Search for a customer name e.g. Debbie
- In the list of results that appear, click a row

Actual result:
- Page refreshes to show the archive id's details in the sidebox, but the rest of the page loses the "Debbie" search and shows all results.

Expected:
- Filters and search results should remain as they were before you click a result row.

I know the code uses $_POST to read filter fields rather than $_GET and doesn't put the filter field values in the URL query parameters, so offhand I'm not sure how much of a rewrite would be required to fix this.

**Comment by neekfenwick** [comment]
While at it: the sidebox heading (white text on black) looks like it uses the wrong printf syntax or something, e.g.  after clicking a row with query param "archive_id=3648930" I see "Archive #%d3648930  -  23/05/2024 09:28:03"

**Comment by drbyte** [comment]
> Search filter values are lost when you click a results row to see details ... $_GET doesn't put the filter field values in the URL query parameters.

Hmmm ... I had converted a lot of $_GET stuff to $_POST to remove the clutter in the URL, and to avoid URL tampering.

Will take another look. Maybe use a $_SESSION var ... although that probably will then beg for a "reset search" button.
